language: c++
sudo: true
dist: trusty

notifications:
  email: false
    # on_success: never
    # on_failure: never

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-sdk-team/ppa'
    - deadsnakes
    - ubuntu-toolchain-r-test
    - chef-current-precise

    packages:
    - cmake
    - time
    - pkg-config
    - python2.7 
    - flex 
    - bison
    - gcc
    - make
    - pkg-config
    - qt5-qmake
    - qtbase5-dev
    # - qtbase5-dev 
    # - qtbase5-dev-tools

cache:
  directories:
  - /opt/ibex
  # - /opt/ibex-geometry
  - /opt/VIBES

matrix:
  include:
  # - os: osx
  #   compiler: clang
  - os: linux
    compiler: gcc 

install:
  - bash ./build_ibex_travis.sh
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex:$HOME/ibex-geometry

script:
  - qmake -project
  - qmake integrationIBEX.pro
  - make -j2
