language: c++
sudo: false

notifications:
  slack:
    on_success: never
    on_failure: never

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - chef-current-precise

    packages:
    - cmake
    - time
    - pkg-config
    - g++-4.8
    - qtbase5-dev 
    - qtbase5-dev-tools

cache:
  directories:
  - $HOME/ibex

matrix:
  include:
  # - os: osx
  #   compiler: clang
  - os: linux
    compiler: gcc-4.8

install:
  - bash ./build_ibex_travis.sh
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex:$HOME/ibex-geometry

script:
 - qmake -project
 - qmake integrationIBEX.pro
 - make
