language: c++
sudo: true
# dist: trusty

notifications:
  email: false
    # on_success: never
    # on_failure: never

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-sdk-team/ppa'
    - deadsnakes
    - ubuntu-toolchain-r-test

    packages:
    - cmake
    - time
    - pkg-config
    - g++-4.8
    - python2.7 
    - flex 
    - bison
    - gcc
    - make
    - pkg-config
    # - qtbase5-dev 
    # - qtbase5-dev-tools

cache:
  directories:
  - $HOME/ibex

matrix:
  include:
  # - os: osx
  #   compiler: clang
  - os: linux
    compiler: gcc-4.8

install:
  - bash ./build_ibex_travis.sh
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex:$HOME/ibex-geometry

script:
 - qmake -project
 - qmake integrationIBEX.pro
 - make
