language: c++
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - chef-current-precise

    packages:
    - cmake
    - time
    - pkg-config
    - g++-4.8
    - qtbase5-dev 
    - qtdeclarative5-dev 
    - libqt5webkit5-dev 
    - libsqlite3-dev
    - qt5-default 
    - qttools5-dev-tools

cache:
  directories:
  - $HOME/ibex

matrix:
  include:
  - os: osx
    compiler: clang
  - os: linux
    compiler: gcc-4.8

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install clang-omp; fi

script:
 - qmake -project
 - qmake integrationIBEX.pro
 - make
